# Smallest base image
FROM resin/%%RESIN_MACHINE_NAME%%-python

# Install GPSD etc
RUN apt-get update && apt-get upgrade -y && apt-get install gpsd
# Update the defaults
RUN sed -i 's/DEVICES=""/DEVICES="\/dev\/ttyAMA0"/g' /etc/default/gpsd

CMD ["cat", "/etc/default/gpsd", "&&", "gpsd", "/dev/ttyAMA0", "-F", "/var/run/gpsd.sock", "&&", "cgps -s"]
