# Smallest base image
FROM resin/%%RESIN_MACHINE_NAME%%-python

# Install GPSD etc
RUN apt-get update && apt-get upgrade -y && apt-get install gpsd gpsd-clients ntpd
# Update the defaults
RUN sed -i 's/DEVICES=""/DEVICES="\/dev\/ttyAMA0"/g' /etc/default/gpsd

COPY startup.sh /usr/local/bin/startup.sh

RUN chmod +x /usr/local/bin/startup.sh

CMD ["/usr/local/bin/startup.sh"]
